using Volo.Abp;

namespace CanteenManagementSystem.EntityFrameworkCore;

public abstract class CanteenManagementSystemEntityFrameworkCoreTestBase : CanteenManagementSystemTestBase<CanteenManagementSystemEntityFrameworkCoreTestModule>
{

}
